import {el,getJSON,fmtDuration} from "/ui/lib.js";
const part=location.pathname.slice(3).split("/director/"),project=decodeURIComponent(part[0]||""),run=decodeURIComponent(part[1]||""),ep=encodeURIComponent(project),er=encodeURIComponent(run),app=document.getElementById("app"),LK=`evedirector.canvas.${project}.${run}`,RK="evedirector.reviewer";
let data,base,work,selected,world,svg,view,opBadge,layout=readLayout(),drag=null;
function cp(v){return JSON.parse(JSON.stringify(v))}function eq(a,b){return JSON.stringify(a)===JSON.stringify(b)}function num(v,d=0){v=Number(v);return Number.isFinite(v)?v:d}function locked(){return !data.model.contract.timeline_editable}function minDur(){return num(data.model.contract.min_scene_duration_seconds,.5)}function scene(id){return work.scenes.find(x=>x.id===id)}function old(id){return base.scenes.find(x=>x.id===id)}
function readLayout(){try{return JSON.parse(localStorage.getItem(LK))||{z:.8,x:60,y:50,p:{}}}catch{return{z:.8,x:60,y:50,p:{}}}}function saveLayout(){localStorage.setItem(LK,JSON.stringify(layout))}
function timeline(){let t=0;for(const s of work.scenes){s.duration_seconds=Math.max(minDur(),num(s.duration_seconds));s.cut.in_seconds=Math.round(t*1000)/1000;t+=s.duration_seconds;s.cut.out_seconds=Math.round(t*1000)/1000}}
function ops(){const out=[],c=data.model.contract;for(const f of c.project_fields||[])if(base.project[f]!==work.project[f])out.push({op:"set_project_field",field:f,value:work.project[f]});const bo=base.scenes.map(s=>s.id),wo=work.scenes.map(s=>s.id);if(!locked()&&!eq(bo,wo))out.push({op:"reorder_scenes",scene_ids:wo});for(const s of work.scenes){const b=old(s.id);if(!locked()&&Math.abs(num(b.duration_seconds)-num(s.duration_seconds))>.0001)out.push({op:"set_scene_duration",scene_id:s.id,duration_seconds:num(s.duration_seconds)});if(b.narration!==s.narration)out.push({op:"set_scene_narration",scene_id:s.id,value:s.narration});for(const f of c.cut_fields||[]){const x=b.cut?.[f]??"",y=s.cut?.[f]??"";if(x!==y)out.push({op:"set_cut_field",scene_id:s.id,field:f,value:String(y)})}}return out}
function badge(){if(opBadge){const n=ops().length;opBadge.textContent=`${n} semantic operation${n===1?"":"s"}`}}
function label(s){return s.cut.title||s.cut.text||s.cut.terminalTitle||s.id}
function select(id){selected=id;renderWorkflow();renderTimeline();renderInspector();document.querySelectorAll(".canvas-node").forEach(n=>n.classList.toggle("selected",n.dataset.sceneId===id))}
function move(id,d){if(locked())return;const i=work.scenes.findIndex(s=>s.id===id),j=i+d;if(i<0||j<0||j>=work.scenes.length)return;work.scenes.splice(j,0,...work.scenes.splice(i,1));timeline();renderWorkflow();renderTimeline();badge()}
function top(){return el("header",{class:"topbar"},el("div",{class:"brand"},el("div",{class:"brand-mark"},"E"),el("div",{},el("h1",{},"EveDirector Unified Workbench"),el("p",{},`${project} · ${run}`))),el("div",{class:"spacer"}),el("div",{class:"toolbar"},el("button",{onclick:()=>zoom(-.1)},"−"),el("button",{onclick:()=>zoom(.1)},"+"),el("button",{onclick:fit},"FIT"),el("button",{onclick:resetLayout},"RESET LAYOUT")),el("span",{class:`pill ${data.actions_enabled?"enabled":"locked"}`},data.actions_enabled?"DERIVE ENABLED":"READ-ONLY"),el("a",{class:"back-link",href:`/p/${ep}/agent-review`},"← Review"))}
function renderWorkflow(){const h=document.getElementById("workflow-list");if(!h)return;h.innerHTML="";work.scenes.forEach((s,i)=>h.append(el("div",{class:`workflow-card${selected===s.id?" selected":""}${!eq(s,old(s.id))?" changed":""}`},el("button",{style:"all:unset;min-width:0;cursor:pointer",onclick:()=>select(s.id)},el("b",{},label(s)),el("small",{},`${s.cut.type} · ${fmtDuration(s.duration_seconds)}`)),el("div",{class:"order-controls"},el("button",{disabled:locked()||i===0,title:locked()?data.model.contract.timeline_lock_reason:"Move earlier",onclick:()=>move(s.id,-1)},"↑"),el("button",{disabled:locked()||i===work.scenes.length-1,title:locked()?data.model.contract.timeline_lock_reason:"Move later",onclick:()=>move(s.id,1)},"↓"))))) }
function defaults(n,i){const m={source:[40,60],canonical:[280,60],candidate:[520,60],validation:[760,60],gate:[1000,60]};if(m[n.id])return{x:m[n.id][0],y:m[n.id][1]};i=Math.max(0,i-5);return{x:130+(i%5)*235,y:280+Math.floor(i/5)*145}}
function transform(){if(world)world.style.transform=`translate(${layout.x}px,${layout.y}px) scale(${layout.z})`}
function center(id){const n=world?.querySelector(`[data-node-id="${CSS.escape(id)}"]`);return n?{x:n.offsetLeft+n.offsetWidth/2,y:n.offsetTop+n.offsetHeight/2}:null}
function edges(){if(!svg)return;svg.innerHTML='<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10z" fill="#536985"/></marker></defs>';for(const e of data.views.canvas.edges||[]){const a=center(e.from),b=center(e.to);if(!a||!b)continue;const p=document.createElementNS("http://www.w3.org/2000/svg","path");p.setAttribute("d",`M${a.x} ${a.y} C${a.x+70} ${a.y},${b.x-70} ${b.y},${b.x} ${b.y}`);svg.append(p)}}
function renderCanvas(){const h=document.getElementById("canvas-host");h.innerHTML='<div class="panel-head"><h2>Infinite Canvas</h2><small>browser-local layout</small></div>';view=el("div",{class:"canvas-viewport"});world=el("div",{class:"canvas-world"});svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.setAttribute("class","canvas-edges");world.append(svg);(data.views.canvas.nodes||[]).forEach((n,i)=>{layout.p[n.id]??=defaults(n,i);const p=layout.p[n.id],s=n.scene_id?scene(n.scene_id):null,node=el("div",{class:`canvas-node ${n.type||"node"}${selected===n.scene_id?" selected":""}${s&&!eq(s,old(s.id))?" changed":""}`,style:`left:${p.x}px;top:${p.y}px`,"data-node-id":n.id,"data-scene-id":n.scene_id||""},el("span",{class:"kind"},n.type||"node"),el("b",{},s?label(s):n.label),el("small",{},s?`${s.cut.type} · ${fmtDuration(s.duration_seconds)}`:n.status||""));node.onpointerdown=e=>{e.stopPropagation();node.setPointerCapture(e.pointerId);drag={t:"node",id:n.id,node,sx:e.clientX,sy:e.clientY,x:p.x,y:p.y,pid:e.pointerId}};node.onclick=()=>n.scene_id&&select(n.scene_id);world.append(node)});view.onpointerdown=e=>{if(e.target!==view)return;view.setPointerCapture(e.pointerId);drag={t:"pan",sx:e.clientX,sy:e.clientY,x:layout.x,y:layout.y,pid:e.pointerId}};view.onwheel=e=>{e.preventDefault();layout.z=Math.max(.25,Math.min(2.5,layout.z*(e.deltaY<0?1.1:.9)));transform();saveLayout()};view.append(world,el("div",{class:"canvas-hint"},"Pan background · wheel zoom · drag nodes locally"));h.append(view);transform();requestAnimationFrame(edges)}
window.addEventListener("pointermove",e=>{if(!drag||e.pointerId!==drag.pid)return;if(drag.t==="pan"){layout.x=drag.x+e.clientX-drag.sx;layout.y=drag.y+e.clientY-drag.sy;transform()}else{const p={x:Math.round(drag.x+(e.clientX-drag.sx)/layout.z),y:Math.round(drag.y+(e.clientY-drag.sy)/layout.z)};layout.p[drag.id]=p;drag.node.style.left=`${p.x}px`;drag.node.style.top=`${p.y}px`;edges()}});window.addEventListener("pointerup",e=>{if(drag&&e.pointerId===drag.pid){drag=null;saveLayout()}})
function zoom(d){layout.z=Math.max(.25,Math.min(2.5,layout.z+d));transform();saveLayout()}function resetLayout(){layout={z:.8,x:60,y:50,p:{}};saveLayout();renderCanvas()}function fit(){const ps=Object.values(layout.p);if(!ps.length)return;const minx=Math.min(...ps.map(p=>p.x)),miny=Math.min(...ps.map(p=>p.y)),maxx=Math.max(...ps.map(p=>p.x+220)),maxy=Math.max(...ps.map(p=>p.y+100));layout.z=Math.max(.25,Math.min(1.2,Math.min((view.clientWidth-40)/(maxx-minx),(view.clientHeight-40)/(maxy-miny))));layout.x=20-minx*layout.z;layout.y=20-miny*layout.z;transform();saveLayout()}
function renderTimeline(){const h=document.getElementById("timeline-scroll");if(!h)return;h.innerHTML="";const track=el("div",{class:"timeline-track"});for(const s of work.scenes){const clip=el("div",{class:`timeline-clip${selected===s.id?" selected":""}${!eq(s,old(s.id))?" changed":""}`,style:`width:${Math.max(64,s.duration_seconds*18)}px`,onclick:()=>select(s.id)},el("b",{},label(s)),el("small",{},`${fmtDuration(s.cut.in_seconds)}–${fmtDuration(s.cut.out_seconds)}`));const input=el("input",{type:"number",min:minDur(),step:.1,value:s.duration_seconds,disabled:locked(),title:locked()?data.model.contract.timeline_lock_reason:"Edit duration",style:"position:absolute;left:9px;bottom:8px;width:66px;background:#08111d;color:#e8eef7;border:1px solid #334760;border-radius:5px"});input.oninput=()=>{if(locked())return;s.duration_seconds=Math.max(minDur(),num(input.value,s.duration_seconds));timeline();badge()};input.onchange=()=>{renderWorkflow();renderTimeline();renderInspector()};clip.append(input);track.append(clip)}h.append(track)}
function field(name,value,fn,multi=false,disabled=false){const x=el(multi?"textarea":"input",{value:value??"",disabled});x.oninput=()=>fn(x.value);return el("label",{class:"field"},el("span",{},name),x)}
function renderInspector(){const h=document.getElementById("inspector-body");if(!h)return;h.innerHTML="";const c=data.model.contract;h.append(el("div",{class:`notice${locked()?"":" safe"}`},locked()?c.timeline_lock_reason:"Ordering and duration are editable; the server rebuilds the timeline."));for(const f of c.project_fields||[])h.append(field(`Project ${f}`,work.project[f],v=>{work.project[f]=v;badge()}));const s=scene(selected);if(s){h.append(el("div",{class:"source-anchor"},el("b",{},`IMMUTABLE · ${s.id}`),el("p",{},s.source_contains)));h.append(field("Narration",s.narration,v=>{s.narration=v;badge()},true));for(const f of c.cut_fields||[])h.append(field(`Cut · ${f}`,s.cut[f]??"",v=>{s.cut[f]=v;badge()},f==="text"||f==="subtitle"));const a=data.views.workflow.find(x=>x.id===s.id)?.source_anchor;if(a)h.append(el("div",{class:"source-anchor"},el("b",{},`SOURCE LINES ${a.line_start}–${a.line_end}`),el("p",{},a.excerpt||a.query||"")))}const reviewer=el("input",{value:localStorage.getItem(RK)||"",placeholder:"Editor name"});reviewer.oninput=()=>localStorage.setItem(RK,reviewer.value);const summary=el("textarea",{placeholder:"Edit summary"});opBadge=el("span",{class:"pill"},"");h.append(el("div",{class:"submit-card"},el("label",{class:"field"},el("span",{},"Editor"),reviewer),el("label",{class:"field"},el("span",{},"Summary"),summary),opBadge,el("button",{class:"secondary",onclick:resetSemantic},"RESET SEMANTIC EDITS"),el("button",{class:"primary",disabled:!data.actions_enabled,onclick:()=>submit(reviewer.value.trim(),summary.value.trim())},"CREATE DERIVED CANDIDATE"),el("div",{class:"notice"},"Canvas positions stay in browser local storage. Only semantic Operations reach L5.")));badge()}
function resetSemantic(){work=cp(base);selected=work.scenes[0]?.id;timeline();renderWorkflow();renderTimeline();renderInspector();renderCanvas()}
async function submit(editor,summary){const operations=ops();if(!editor)return error("Editor identity is required.");if(!operations.length)return error("No semantic Operations are staged; canvas layout is local-only.");if(!confirm(`Create a Derived Run with ${operations.length} operation(s)?\n\n${data.authority.confirmation}`))return;try{const r=await fetch(data.authority.derive_endpoint,{method:"POST",headers:{"Content-Type":"application/json","X-EveDirector-Action":"review"},body:JSON.stringify({reviewer:editor,summary,confirmation:data.authority.confirmation,operations})}),p=await r.json().catch(()=>({}));if(!r.ok)throw Error(p.detail||`${r.status} derive`);location.href=`/p/${ep}/agent-review`}catch(e){error(e.message||String(e))}}
function error(t){let b=document.getElementById("director-error");if(!b){b=el("div",{id:"director-error",class:"error"});app.insertBefore(b,app.children[1]||null)}b.textContent=t}
function shell(){app.innerHTML="";app.append(top(),el("div",{class:"workspace"},el("section",{class:"panel workflow-panel"},el("div",{class:"panel-head"},el("h2",{},"Workflow"),el("small",{},"shared scene lane")),el("div",{id:"workflow-list",class:"workflow-list"})),el("section",{id:"canvas-host",class:"panel canvas-panel"}),el("aside",{class:"panel inspector-panel"},el("div",{class:"panel-head"},el("h2",{},"Inspector & Authority")),el("div",{id:"inspector-body",class:"inspector-body"})),el("section",{class:"panel timeline-panel"},el("div",{class:"panel-head"},el("h2",{},"Timeline"),el("small",{},"same scene model")),el("div",{id:"timeline-scroll",class:"timeline-scroll"}))));renderWorkflow();renderCanvas();renderTimeline();renderInspector()}
(async()=>{try{data=await getJSON(`/api/project/${ep}/director/${er}`);base=cp(data.model);work=cp(data.model);selected=work.scenes[0]?.id;timeline();shell()}catch(e){app.append(el("div",{class:"error"},e.message||String(e)))}})();
